apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-sub
  labels:
    app: nats-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-sub
  template:
    metadata:
      labels:
        app: nats-sub
    spec:
      containers:
      - name: nats-sub
        image: smvfal/nats-sub:latest
        env:
          - name: NATS_URL
            value: "http://nats.openfaas:4222"
          - name: SUBJECT
            value: "metrics"
